services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/islasgeci.org_setup:latest
    command: make
    volumes:
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
