---
- name: Set system up
  hosts: webserver
  tasks:
    - name: Set time zone
      timezone:
        name: America/Los_Angeles
      become: true

- name: Install software using package managers
  hosts: webserver
  tasks:
    - name: Update system
      apt:
        update_cache: true
      become: true
    - name: Install cURL
      apt:
        name: "curl"
        state: present
      become: true
    - name: Install Docker
      apt:
        name: "docker.io"
        state: present
      become: true
    - name: Install Docker-compose
      apt:
        name: "docker-compose"
        state: present
      become: true
    - name: Install Git
      apt:
        name: "git"
        state: present
      become: true
    - name: Install Make
      apt:
        name: "make"
        state: present
      become: true
    - name: Install pip
      apt:
        name: "python3-pip"
        state: present
      become: true
    - name: Install Docker SDK for Python
      pip:
        name: docker
      notify: Restart server
    - name: Add '{{ ansible_user_id }}' to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      become: true
      notify: Restart server
  handlers:
    - name: Restart server
      reboot:
      become: true

- name: Run Web Server container
  hosts: webserver
  tasks:
    - name: Create work directory for geci-testmake
      ansible.builtin.file:
        path: /home/ciencia_datos/.testmake
        state: directory
        recurse: yes
        owner: ciencia_datos
        group: ciencia_datos
    - name: Copy SSH keys
      copy:
        src: /root/.ssh/id_rsa
        dest: /tmp/id_rsa
        mode: '0600'
    - name: Copy secrets
      copy:
        src: /root/.vault/
        dest: /home/ciencia_datos/.vault/
        mode: '0600'
    - name: Start the container
      community.docker.docker_container:
        name: islasgeci.org
        image: islasgeci/islasgeci.org:latest
        state: started
        restart_policy: "always"
        detach: true
        volumes:
          - /home/ciencia_datos/.testmake:/home/ciencia_datos/.testmake
          - /home/ciencia_datos/.vault/.secrets:/home/ciencia_datos/.vault/.secrets
          - /tmp/id_rsa:/root/.ssh/id_rsa
          - /var/run/docker.sock:/var/run/docker.sock
